version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: twitty_admin
      POSTGRES_PASSWORD: twitty12345
      POSTGRES_DB: twitty_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: database
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  pgdata: